PUT http://localhost:3001/api/readinglists/4
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxzc2lAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTY2MjAzNTQxOX0.s55MQ2HzjSN0sc9z80uK2I51A3KJR9GSK6Quchz-VN4

{
  "read": true
}